# This files purpose is to fix the ui.py file generated by pyuic5 to be compatible with PyQt6
# The pyuic5 command to convert the ui file is: pyuic5 -o ui.ui ui.py


import re

def fix_ui_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as file:
        content = file.read()

    # Fix frame shape and shadow syntax
    content = re.sub(r'QtCore.Qt.QFrame::Shape::', 'QtWidgets.QFrame.', content)
    content = re.sub(r'QtCore.Qt.QFrame::Shadow::', 'QtWidgets.QFrame.', content)
    content = re.sub(r'QtCore.Qt.Qt::AlignmentFlag::', 'QtCore.Qt.', content)
    content = re.sub(r'QtCore.Qt.Qt::LayoutDirection::', 'QtCore.Qt.', content)

    # Fix alignment issues
    content = re.sub(r'QtCore.Qt.AlignRight\|QtCore.Qt.AlignTrailing\|QtCore.Qt.AlignVCenter', 'QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter', content)
    content = re.sub(r'QtCore.Qt.AlignRight\|QtCore.Qt.AlignTrailing\|QtCore.Qt.AlignVCenter', 'QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter', content)

    with open(filepath, 'w', encoding='utf-8') as file:
        file.write(content)

if __name__ == "__main__":
    fix_ui_file('ui.py')
    print("ui.py has been fixed.")
