# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capture_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 768)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonCaptureImage = QtWidgets.QPushButton(Dialog)
        self.buttonCaptureImage.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCaptureImage.setFont(font)
        self.buttonCaptureImage.setObjectName("buttonCaptureImage")
        self.gridLayout.addWidget(self.buttonCaptureImage, 2, 0, 1, 1)
        self.buttonReloadList = QtWidgets.QPushButton(Dialog)
        self.buttonReloadList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonReloadList.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonReloadList.setObjectName("buttonReloadList")
        self.gridLayout.addWidget(self.buttonReloadList, 3, 1, 1, 1)
        self.listImages = QtWidgets.QListView(Dialog)
        self.listImages.setObjectName("listImages")
        self.gridLayout.addWidget(self.listImages, 0, 1, 1, 1)
        self.lineeditImageName = QtWidgets.QLineEdit(Dialog)
        self.lineeditImageName.setObjectName("lineeditImageName")
        self.gridLayout.addWidget(self.lineeditImageName, 1, 0, 1, 1)
        self.buttonQuit = QtWidgets.QPushButton(Dialog)
        self.buttonQuit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonQuit.setFont(font)
        self.buttonQuit.setObjectName("buttonQuit")
        self.gridLayout.addWidget(self.buttonQuit, 5, 0, 1, 1)
        self.canvasCamera = QtWidgets.QGraphicsView(Dialog)
        self.canvasCamera.setObjectName("canvasCamera")
        self.gridLayout.addWidget(self.canvasCamera, 0, 0, 1, 1)
        self.buttonSwitchCamera = QtWidgets.QPushButton(Dialog)
        self.buttonSwitchCamera.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonSwitchCamera.setFont(font)
        self.buttonSwitchCamera.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonSwitchCamera.setObjectName("buttonSwitchCamera")
        self.gridLayout.addWidget(self.buttonSwitchCamera, 3, 0, 1, 1)
        self.buttonEditImage = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonEditImage.setFont(font)
        self.buttonEditImage.setObjectName("buttonEditImage")
        self.gridLayout.addWidget(self.buttonEditImage, 1, 1, 1, 1)
        self.labelConsole = QtWidgets.QLabel(Dialog)
        self.labelConsole.setMinimumSize(QtCore.QSize(0, 75))
        self.labelConsole.setFrameShape(QtWidgets.QFrame.Box)
        self.labelConsole.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelConsole.setText("")
        self.labelConsole.setObjectName("labelConsole")
        self.gridLayout.addWidget(self.labelConsole, 4, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonCaptureImage.setText(_translate("Dialog", "Capture Image"))
        self.buttonReloadList.setText(_translate("Dialog", "Reload List"))
        self.lineeditImageName.setPlaceholderText(_translate("Dialog", "Image Name"))
        self.buttonQuit.setText(_translate("Dialog", "Quit"))
        self.buttonSwitchCamera.setText(_translate("Dialog", "Switch Camera"))
        self.buttonEditImage.setText(_translate("Dialog", "Edit Image"))
